-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Person"
(
    person_id integer NOT NULL,
    first_name character varying(50)[] NOT NULL,
    last_name character varying(50)[] NOT NULL,
    date_of_birth date NOT NULL,
    phone character varying(20)[] NOT NULL,
    email character varying(255)[] NOT NULL,
    PRIMARY KEY (person_id)
);

COMMENT ON TABLE public."Person"
    IS 'Superclass';

CREATE TABLE IF NOT EXISTS public."Doctor"
(
    doctor_id integer NOT NULL,
    person_id integer NOT NULL,
    specialty_id integer NOT NULL,
    PRIMARY KEY (doctor_id)
);

CREATE TABLE IF NOT EXISTS public."Specialty"
(
    specialty_id integer NOT NULL,
    specialty_name character varying(52)[],
    PRIMARY KEY (specialty_id),
    CONSTRAINT specialty_name UNIQUE (specialty_name)
        INCLUDE(specialty_name)
);

ALTER TABLE IF EXISTS public."Doctor"
    ADD CONSTRAINT person_id FOREIGN KEY (person_id)
    REFERENCES public."Person" (person_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Doctor"
    ADD CONSTRAINT specialty_id FOREIGN KEY (specialty_id)
    REFERENCES public."Specialty" (specialty_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;