-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Person"
(
    person_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    first_name character varying(50)[] NOT NULL,
    last_name character varying(50)[] NOT NULL,
    date_of_birth date NOT NULL,
    phone character varying(20)[] NOT NULL,
    email character varying(255)[] NOT NULL,
    PRIMARY KEY (person_id)
);

COMMENT ON TABLE public."Person"
    IS 'Superclass';

CREATE TABLE IF NOT EXISTS public."Doctor"
(
    doctor_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    person_id integer NOT NULL,
    specialty_id integer NOT NULL,
    hire_date date NOT NULL,
    license_no character varying(7),
    PRIMARY KEY (doctor_id),
    CONSTRAINT license_no UNIQUE (license_no)
        INCLUDE(license_no)
);

CREATE TABLE IF NOT EXISTS public."Specialty"
(
    specialty_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    specialty_name character varying(52)[],
    PRIMARY KEY (specialty_id),
    CONSTRAINT specialty_name UNIQUE (specialty_name)
        INCLUDE(specialty_name)
);

CREATE TABLE IF NOT EXISTS public."Emergency_Contact"
(
    emergency_contact_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    patient_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    relationship character varying(50),
    phone character varying(20),
    PRIMARY KEY (emergency_contact_id)
);

CREATE TABLE IF NOT EXISTS public."Patient"
(
    patient_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    person_id integer NOT NULL,
    healh_card_no character varying(12),
    address character varying(50),
    PRIMARY KEY (patient_id)
);

CREATE TABLE IF NOT EXISTS public."Appointment"
(
    appointment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    appointment_datetime date NOT NULL,
    reason character varying(500),
    status character varying(20) NOT NULL,
    PRIMARY KEY (appointment_id),
    CONSTRAINT patient_id UNIQUE (patient_id)
        INCLUDE(patient_id),
    CONSTRAINT doctor_id UNIQUE (doctor_id)
        INCLUDE(doctor_id),
    CONSTRAINT appointment_datetime UNIQUE (appointment_datetime)
        INCLUDE(patient_id, doctor_id)
);

CREATE TABLE IF NOT EXISTS public."Visit"
(
    visit_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    appointment_id integer NOT NULL,
    diagnosis character varying(255),
    treatment character varying(255),
    visit_date date NOT NULL,
    PRIMARY KEY (visit_id),
    CONSTRAINT appointment_id UNIQUE (appointment_id)
);

CREATE TABLE IF NOT EXISTS public."Bill"
(
    bill_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    amount numeric(10, 2) NOT NULL,
    payment_status character varying(20) NOT NULL,
    PRIMARY KEY (bill_id)
);

CREATE TABLE IF NOT EXISTS public."Medical_History"
(
    history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    patient_id integer NOT NULL,
    visit_id integer NOT NULL,
    recorded_on date NOT NULL,
    notes character varying(500),
    PRIMARY KEY (history_id)
);

ALTER TABLE IF EXISTS public."Doctor"
    ADD CONSTRAINT person_id FOREIGN KEY (person_id)
    REFERENCES public."Person" (person_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Doctor"
    ADD CONSTRAINT specialty_id FOREIGN KEY (specialty_id)
    REFERENCES public."Specialty" (specialty_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Emergency_Contact"
    ADD CONSTRAINT patient_id FOREIGN KEY (patient_id)
    REFERENCES public."Patient" (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Patient"
    ADD CONSTRAINT person_id FOREIGN KEY (person_id)
    REFERENCES public."Person" (person_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Appointment"
    ADD CONSTRAINT patient_id FOREIGN KEY (patient_id)
    REFERENCES public."Patient" (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Appointment"
    ADD CONSTRAINT doctor_id FOREIGN KEY (doctor_id)
    REFERENCES public."Doctor" (doctor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Visit"
    ADD CONSTRAINT appointment_id FOREIGN KEY (appointment_id)
    REFERENCES public."Appointment" (appointment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bill"
    ADD CONSTRAINT visit_id FOREIGN KEY (visit_id)
    REFERENCES public."Visit" (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bill"
    ADD CONSTRAINT patient_id FOREIGN KEY (patient_id)
    REFERENCES public."Patient" (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bill"
    ADD CONSTRAINT doctor_id FOREIGN KEY (doctor_id)
    REFERENCES public."Doctor" (doctor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Medical_History"
    ADD CONSTRAINT patient_id FOREIGN KEY (patient_id)
    REFERENCES public."Patient" (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Medical_History"
    ADD CONSTRAINT visit_id FOREIGN KEY (visit_id)
    REFERENCES public."Visit" (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;