--- Advanced Database Activity 2
--- Drew Temple-Smith, Kyle Castillo, Brayden Nickel, Ethan Pelletier

BEGIN;

CREATE TABLE IF NOT EXISTS public.person
(
    person_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    date_of_birth date NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(255) NOT NULL,
    PRIMARY KEY (person_id)
);

COMMENT ON TABLE public.person
    IS 'Superclass';

CREATE TABLE IF NOT EXISTS public.doctor
(
    doctor_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    person_id integer NOT NULL,
    specialty_id integer NOT NULL,
    hire_date date NOT NULL,
    license_no character varying(7),
    PRIMARY KEY (doctor_id),
    CONSTRAINT license_no UNIQUE (license_no)
);

CREATE TABLE IF NOT EXISTS public.specialty
(
    specialty_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    specialty_name character varying(52),
    PRIMARY KEY (specialty_id),
    CONSTRAINT specialty_name UNIQUE (specialty_name)
);

CREATE TABLE IF NOT EXISTS public.emergency_contact
(
    emergency_contact_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    patient_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    relationship character varying(50),
    phone character varying(20),
    PRIMARY KEY (emergency_contact_id)
);

CREATE TABLE IF NOT EXISTS public.patient
(
    patient_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    person_id integer NOT NULL,
    health_card_no character varying(12),
    address character varying(50),
    PRIMARY KEY (patient_id)
);

CREATE TABLE IF NOT EXISTS public.appointment
(
    appointment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    appointment_datetime timestamp NOT NULL,
    reason character varying(500),
    status character varying(20) NOT NULL,
    PRIMARY KEY (appointment_id),
    CONSTRAINT doctor_time_slot UNIQUE (doctor_id, appointment_datetime)
);

CREATE TABLE IF NOT EXISTS public.visit
(
    visit_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    appointment_id integer NOT NULL,
    diagnosis character varying(255),
    treatment character varying(255),
    visit_date date NOT NULL,
    PRIMARY KEY (visit_id),
    CONSTRAINT one_visit_per_appointment UNIQUE (appointment_id)
);

CREATE TABLE IF NOT EXISTS public.bill
(
    bill_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    amount numeric(10, 2) NOT NULL,
    payment_status character varying(20) NOT NULL,
    PRIMARY KEY (bill_id)
);

CREATE TABLE IF NOT EXISTS public.medical_history
(
    history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    patient_id integer NOT NULL,
    visit_id integer NOT NULL,
    recorded_on date NOT NULL,
    notes character varying(500),
    PRIMARY KEY (history_id)
);

ALTER TABLE IF EXISTS public.doctor
    ADD CONSTRAINT person_id FOREIGN KEY (person_id)
    REFERENCES public.person (person_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.doctor
    ADD CONSTRAINT specialty_id FOREIGN KEY (specialty_id)
    REFERENCES public.specialty (specialty_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.emergency_contact
    ADD CONSTRAINT patient_id FOREIGN KEY (patient_id)
    REFERENCES public.patient (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.patient
    ADD CONSTRAINT person_id FOREIGN KEY (person_id)
    REFERENCES public.person (person_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT patient_id FOREIGN KEY (patient_id)
    REFERENCES public.patient (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT doctor_id FOREIGN KEY (doctor_id)
    REFERENCES public.doctor (doctor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.visit
    ADD CONSTRAINT appointment_id FOREIGN KEY (appointment_id)
    REFERENCES public.appointment (appointment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bill
    ADD CONSTRAINT visit_id FOREIGN KEY (visit_id)
    REFERENCES public.visit (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bill
    ADD CONSTRAINT patient_id FOREIGN KEY (patient_id)
    REFERENCES public.patient (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bill
    ADD CONSTRAINT doctor_id FOREIGN KEY (doctor_id)
    REFERENCES public.doctor (doctor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.medical_history
    ADD CONSTRAINT patient_id FOREIGN KEY (patient_id)
    REFERENCES public.patient (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.medical_history
    ADD CONSTRAINT visit_id FOREIGN KEY (visit_id)
    REFERENCES public.visit (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;